### ISSUE TITLE
Error while creating cohort

### ISSUE THREAD

**Issue by pm-ibm** [chgl/charts#148]
I get following error while creating a cohort. Any suggestion on where the issue might be?

```
2021-10-29 22:21:24.229 ERROR http-nio-8080-exec-4 org.ohdsi.webapi.util.GenericExceptionMapper -  - java.lang.NoClassDefFoundError: org/graalvm/polyglot/PolyglotException
	at org.ohdsi.analysis.versioning.CdmVersionUtils.determineCdmCompatibility(CdmVersionUtils.java:27)
	at org.ohdsi.analysis.versioning.VersionedSerializer.serialize(VersionedSerializer.java:21)
	at org.ohdsi.analysis.versioning.VersionedSerializer.serialize(VersionedSerializer.java:9)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:292)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3697)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3073)
	at org.ohdsi.analysis.Utils.serialize(Utils.java:172)
	at org.ohdsi.analysis.Utils.serialize(Utils.java:165)
	at org.ohdsi.webapi.service.CohortDefinitionService.createCohortDefinition(CohortDefinitionService.java:406)
	at org.ohdsi.webapi.service.CohortDefinitionService$$FastClassBySpringCGLIB$$3ea7ee83.invoke(<generated>)
```

**Comment by chgl** [comment]
Thank you for reporting the issue! I'm not entirely sure this is related to the helm chart specifically. Just from looking at the names of the associated classes, maybe some version string inside the CDM is missing or improperly set. Are you using the latest version of the chart and its components?

**Comment by pm-ibm** [comment]
When you mention `some version string inside the CDM is missing or improperly set` where exactly should I look for? Are you referring to value of source_key column in  `ohdsi.source` table (as set in cdmInitJob) or something else as well?

**Comment by chgl** [comment]
I think this issue is better placed in https://github.com/OHDSI/WebAPI/issues. My idea about the version string in ohdsi.source is most likely wrong.
